name: Publish to npm

on:
  push:
    branches:
      - main
    tags:
      - "v*.." # Publica cuando se crea una nueva etiqueta (versión semántica)

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16" # o la versión de Node.js que estés usando
          registry-url: "https://registry.npmjs.org"

      - name: Install dependencies
        run: npm install

      #- name: Run tests
      #  run: npm test

      - name: Publish to npm
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
